theme: jekyll-theme-minimal
title: Maitai K.
description: Continually curiousity-driven data learner. I believe in logical and creativity integrated thinking process.
  3 Years work experience in architectural design field in Washington DC and 2 years in Bangkok.
  My background, skills together with my strong motivation will complement the team.  
url-pretty: "MyWebsite.com"
