theme: jekyll-theme-minimal
title: Maitai K.
description: Continually curiousity-driven data learner. I believe in logical and creativity integrated thinking process. \
3 Years work experience in architectural design field in Washington DC and 2 years in Bangkok.

[Getting to know me through my CV!](www.)
